apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: krustyapp
  name: krustyapp
  namespace: default
spec:
  selector:
    matchLabels:
      app: krustyapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: drafttest.azurecr.io/drafttest
        name: krustyapp
        resources: {}
status: {}
