apiVersion: apps/v1
kind: Deployment
metadata:
  name: draftdemo
  labels:
    app: draftdemo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: draftdemo
  template:
    metadata:
      labels:
        app: draftdemo
    spec:
      containers:
        - name: draftdemo
          image: draftdemo:latest
          ports:
            - containerPort: 8080