apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: manifestapp
  name: manifestapp
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: manifestapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: manifestapp
    spec:
      containers:
      - image: .azurecr.io/
        name: manifestapp
        ports:
        - containerPort: 8080
        resources: {}
status: {}
