apiVersion: v1
kind: Service
metadata:
  name: manifestapp
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: manifestapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080