apiVersion: v1
kind: Service
metadata:
  name: davidgamero-test
  namespace: namespace-workflow-1691679642421
spec:
  type: LoadBalancer
  selector:
    app: davidgamero-test
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080